---
url: 		'http://localhost:4000'
baseurl: 	''
urlimg: 	'http://localhost:4000/images/'

# See › https://github.com/jekyll/jekyll-gist#disabling-noscript-support
gist:
  noscript: false

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true