# Site settings
title: acesubido
baseurl: "http://ace-subido.github.io" # the subpath of your site, e.g. /blog/
url: "http://acesubido.com" # the base hostname & protocol for your site
twitter_username: acesubido
github_username:  ace-subido
paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
gems: [bourbon, neat]
highlighter: pygments
