# Site settings
title: acesubido
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acesubido.com" # the base hostname & protocol for your site
twitter_username: acesubido
github_username: ace-subido
paginate: 10
paginate_path: "/page/:num/"
source: "src/"
destination: "_site/"
plugins_dir: "src/_plugins"
gems: [jekyll-paginate, jekyll-compose]

# Build settings
markdown: kramdown
gems: [bourbon, neat]
highlighter: pygments
slim:
  pretty: true
  format: html5
